export const data = [
    {
        title: "Moana",
        category: "Western",
        id: Math.random(),
        rate: 8,
        cover: "https://m.media-amazon.com/images/I/A1JOaV3B6fL._AC_SL1500_.jpg",
        cast: "Jemaine Clement, Rachel House",
        release: "2012-12-25",
    },
    {
        title: "Coco",
        category: "Mistery",
        id: Math.random(),
        rate: 7,
        cover: "https://lumiere-a.akamaihd.net/v1/images/p_coco_19736_fd5fa537.jpeg?region=0%2C0%2C540%2C810",
        cast: "Samuel L.Jackson, Kurt Russel, Jennifer Jason Leigh",
        release: "2015-12-30 ",
    },
    {
        title: "Encanto",
        category: "Drama",
        id: Math.random(),
        rate: 7,
        cover: "https://media.services.cinergy.ch/media/box1600/97e60f91f99241efea976da057a2235a1bd078e1.jpg",
        cast: "Anthony Gonzalez,Ana Ofelia Murguía",
        release: "2019-07-26",
    },
    {
        title: "Raya and the last dragon",
        category: "War",
        id: Math.random(),
        rate: 8,
        cover: "https://m.media-amazon.com/images/M/MV5BZWNiOTc4NGItNGY4YS00ZGNkLThkOWEtMDE2ODcxODEwNjkwXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg",
        cast: " Brad Pitt, Diane Kruger, Eli Roth",
        release: "2009-08-20",
    },
    {
        title: "Dragon Ball",
        category: "Crime",
        id: Math.random(),
        rate: 9,
        cover: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjSvnJc2ChhO9Y6LsuBKeLmzPw8zekDqEB2w&usqp=CAU",
        cast: " Uma Thurman, David Carradine, Daryl Hannah",
        release: "2003-10-10",
    },
   
];
