export const data = [
    {
        title: "Django Unchained",
        category: "Western",
        id: Math.random(),
        rate: 8,
        cover: "https://m.media-amazon.com/images/I/71ZTyvsUBXS._AC_SY679_.jpg",
        cast: "Jamie Foxx, Leonardo DiCaprio, Christoph Waltz",
        release: "2012-12-25",
    },
    {
        title: "The Hateful Eight",
        category: "Mistery",
        id: Math.random(),
        rate: 7,
        cover: "https://c8.alamy.com/comp/FX7KBR/the-hateful-eight-year-2015-usa-director-quentin-tarantino-movie-poster-FX7KBR.jpg",
        cast: "Samuel L.Jackson, Kurt Russel, Jennifer Jason Leigh",
        release: "2015-12-30 ",
    },
    {
        title: "Once Upon a Time in Hollywood",
        category: "Drama",
        id: Math.random(),
        rate: 7,
        cover: "https://m.media-amazon.com/images/M/MV5BOTg4ZTNkZmUtMzNlZi00YmFjLTk1MmUtNWQwNTM0YjcyNTNkXkEyXkFqcGdeQXVyNjg2NjQwMDQ@._V1_FMjpg_UX1000_.jpg",
        cast: "Leonardo DiCaprio, Brad Pitt, Margot Robbie",
        release: "2019-07-26",
    },
    {
        title: "Inglourious Basterds",
        category: "War",
        id: Math.random(),
        rate: 8,
        cover: "https://m.media-amazon.com/images/I/61PXdxTJGPL._AC_SY741_.jpg",
        cast: " Brad Pitt, Diane Kruger, Eli Roth",
        release: "2009-08-20",
    },
    {
        title: "Kill Bill Vol. 1",
        category: "Crime",
        id: Math.random(),
        rate: 9,
        cover: "https://m.media-amazon.com/images/I/81Az82YYZaS._AC_SL1500_.jpg",
        cast: " Uma Thurman, David Carradine, Daryl Hannah",
        release: "2003-10-10",
    },
    {
        title: "Pulp Fiction",
        category: "Drama",
        id: Math.random(),
        rate: 9,
        cover: "https://cdn.shopify.com/s/files/1/0482/3452/8936/products/Pulp-Fiction-Poster-Films-Vibez-1604865213_ffcfc34b-b53f-4da0-873a-9a518eb0746f.jpg?v=1604865494",
        cast: "John Travolta, Uma Thurman, Samuel L. Jackson",
        release: "1994-10-14",
    },
    {
        title: "Jackie Brown",
        category: "Crime",
        id: Math.random(),
        rate: 6,
        cover: "https://cdn.shopify.com/s/files/1/1416/8662/products/JackieBrown_1997_original_film_art_bcad0eb7-06a6-46e0-9e36-b1de44cf3036_1200x.jpg?v=1643239190",
        cast: "Pam Grier, Samuel L. Jackson, Robert Forster",
        release: "1997-12-25",
    },
    {
        title: "Kill Bill 2",
        category: "Crime",
        id: Math.random(),
        rate: 8,
        cover: "https://c8.alamy.com/comp/BKGG4D/kill-bill-volume-2-2004-poster-kbl2-002-post1-BKGG4D.jpg",
        cast: "Uma Thurman, David Carradine, Michael Madsen",
        release: "2004-04-16",
    },
];
